[book]
authors = ["ian-hamlin"]
language = "en"
multilingual = false
src = "src"
title = "Recipes"
description = "A collection of recipes"

[output.html]
no-section-label = true

[build]
build-dir = "docs"